export const MOCK_DORMS = [
  {
    id: 1,
    slug: 'greenview-45',
    name: 'หอพักกรีนวิว',
    imageUrl: 'https://sa.ku.ac.th/wp-content/uploads/2025/06/%E0%B8%AB%E0%B8%AD%E0%B9%81%E0%B8%AA%E0%B8%87%E0%B8%88%E0%B8%B1%E0%B8%99%E0%B8%97%E0%B8%A3%E0%B9%8C.jpg',
    price: 3500,
    locationShort: 'ซอยพหลโยธิน 45 (ใกล้ ม. 500 ม.)',
    rating: 4.5,
    reviewCount: 32,
    tags: ['ใกล้มหาลัย', 'ของกินเยอะ', 'เดินทางสะดวก'],
    facilities: ['wifi', 'security', 'parking'] as ('wifi' | 'security' | 'parking')[],
    isVerified: true,
  },
  {
    id: 2,
    slug: 'the-cozy-hub',
    name: 'The Cozy Hub Resident',
    imageUrl: '/mock/dorm2.jpg',
    price: 4200,
    locationShort: 'หน้าซอยงามวงศ์วาน 52',
    rating: 4.8,
    reviewCount: 128,
    tags: ['ห้องกว้าง', 'ใหม่มาก', 'เงียบสงบ'],
    facilities: ['wifi', 'security'] as ('wifi' | 'security')[],
    isVerified: true,
  },
  {
    id: 3,
    slug: 'metro-loft',
    name: 'Metro Loft Student Living',
    imageUrl: '/mock/dorm3.jpg',
    price: 5500,
    locationShort: 'ติด BTS สถานีมหาวิทยาลัย',
    rating: 4.2,
    reviewCount: 56,
    tags: ['ติดรถไฟฟ้า', 'ฟิตเนส', 'หรูหรา'],
    facilities: ['wifi', 'security', 'parking'] as ('wifi' | 'security' | 'parking')[],
    isVerified: false,
  },
  {
    id: 4,
    slug: 'baan-suan',
    name: 'บ้านสวน เรสซิเดนซ์',
    imageUrl: '/mock/dorm4.jpg',
    price: 2800,
    locationShort: 'ซอยข้างโรงพยาบาล (เข้าซอยลึก)',
    rating: 3.9,
    reviewCount: 14,
    tags: ['ราคาประหยัด', 'บรรยากาศดี', 'เลี้ยงสัตว์ได้'],
    facilities: ['wifi', 'parking'] as ('wifi' | 'parking')[],
    isVerified: false,
  },
];